### PR TITLE
npm support

### PR DESCRIPTION
**Pull request by AmateurPotion**

### CODE REVIEW

**Comment by AmateurPotion** [comment]
My mistake on npm command. I'll update it.

**Comment by Anuken** [comment]
This is a *Java* project, what does it have to do with NPM?

**Comment by AmateurPotion** [comment]
If you can afford it later, I'd like you to upload this mod package on npm package like create-react-app so that you can create a project with one command.

**Comment by AmateurPotion** [comment]
Your game is very helpful to study Java.

**Comment by Anuken** [comment]
But that doesn't make any sense. NPM is for *Javascript* libraries, this doesn't belong there. If you want to create a project templating tool, write a separate application or script that can set it up with one command. It doesn't need to be in this repository.

**Comment by AmateurPotion** [comment]
ok...

**Pull request closed without merging**
